server:
  port: 9090
#server.address: 127.0.0.1

spring:
  application:
    name: resource-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/  
      
security:
  oauth2:
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      clientId: acme
#      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user

logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.security.web.util.matcher: OFF
      